# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [11]:
# Import torch
import torch
print(torch.__version__)

# Create random tensor
mat1 = torch.randn(7,7)
mat1

2.7.0+cu118


tensor([[-1.1012,  1.2352,  0.2200,  1.4564,  0.4352, -0.4690, -0.3938],
        [ 0.3103,  1.4793, -1.3539,  0.8877, -0.9999,  0.2869,  0.9202],
        [ 0.0350, -0.6321,  1.9651,  1.8399, -3.0004,  0.0691,  0.5688],
        [-1.3492,  0.1506,  1.2561, -0.6416,  1.1943,  2.2369,  0.6318],
        [-0.1344,  1.1929,  0.3758, -1.4770, -0.8006, -0.5058,  0.1320],
        [-1.7834, -0.4750, -0.4430, -1.7161, -1.1880, -0.5064,  1.6547],
        [ 0.3307, -0.1294, -1.1235,  0.1977,  0.5086,  0.3008,  0.4549]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [24]:
# Create another random tensor
mat2 = torch.randn(1,7)
mat2

mat3 = mat2.transpose(-2, 1)
print(mat3)

print(mat3.shape, mat3.size)

# Perform matrix multiplication 

mat2 @ mat3

tensor([[-0.7183],
        [-1.4382],
        [-1.1726],
        [-1.9269],
        [ 0.5397],
        [ 0.3025],
        [ 0.3534]])
torch.Size([7, 1]) <built-in method size of Tensor object at 0x711be871f570>


tensor([[8.1800]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [34]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
ran1 = torch.rand(size=(7, 7))
ran2 = torch.rand(size=(7, 1))

# Matrix multiply tensors
ran3 = ran1 @ ran2
print(ran3)
ran3.shape


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


torch.Size([7, 1])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [35]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [45]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tnsr1 = torch.rand(size=(2,3)).to(device)
tnsr2 = torch.rand(size=(2,3)).to(device)

print(tnsr1, tnsr2)


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [49]:
# Perform matmul on tensor_A and tensor_B

tnsr3 = tnsr2.transpose(-2, 1)

tnsr4 = tnsr1 @ tnsr3

tnsr4, tnsr4.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [53]:
# Find max
print(torch.max(tnsr4))

# Find min
print(torch.min(tnsr4))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [55]:
# Find arg max
max_idx = torch.argmax(tnsr4)

# Find arg min
min_idx = torch.argmin(tnsr4)
print(max_idx, min_idx)

tensor(3, device='cuda:0') tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [59]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tnsr5 = torch.rand(size=(1, 1, 1, 10))
# tnsr5
# Remove single dimensions
tnsr6 = tnsr5.squeeze()

# Print out tensors
print(tnsr4, tnsr5)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
